---
title: "Oversikt over emneansvarlige"
format: html
---



```{r}
#| echo: false
#| warning: false
#| message: false
library(tidyverse)
library(lubridate)
library(gt)
library(stringr)

budsjett <- readRDS("data/timebudsjett.rds")

emneansvarlige <- budsjett %>% 
  #filter(str_sub(emne,1,3) %in% c("SOS", "KUL", "SVL", "SVM", "OLA", "UTV", "SGO", "HGO")) %>% 
  # mutate(semester = ifelse(str_sub(aar,-1,-1) == "V", 1, 2),
  #        aar = str_sub(aar,1,4)) %>% 
  filter( tolower(aktivitet) == "emneansvar") %>% 
  select(aar, semester, emne, navn) %>% 
  # kilde: https://stackoverflow.com/questions/52120034/extract-first-letter-in-each-word-in-r
  mutate(initialer = gsub('\\b(\\pL)\\pL{2,}|.','\\U\\1', navn, perl = TRUE)) %>%  
  mutate(navn = paste( str_sub(initialer, 1, -2), word(navn, -1))) %>%
  select(-initialer) %>% 
  group_by(aar, semester, emne) %>% 
  summarise(navn = paste(navn, collapse = " & "))  %>% 
  arrange(aar, desc(semester), emne) %>%
  pivot_wider(names_from = c(aar, semester), values_from = navn, names_sort = TRUE) %>% 
  ungroup()


```



```{r}
#| echo: false
#| warning: false
#| message: false

sluttaar <- paste0(lubridate::year(Sys.Date())+3, "_2")

emneansvarlige %>%
  select(emne,  ends_with("2")) %>%
  select(- 2) %>% 
  select(emne:sluttaar) %>% 
  filter( !is.na(.[,2]) ) %>%  
  gt(rowname_col = "emne", groupname_col = "semester") %>% 
  sub_missing(columns = everything(),
              rows = everything(),
              missing_text = " " ) %>% 
  cols_align(align = "right") %>% 
  tab_header(title = "Emneansvarlige høstsemester", subtitle = "Utfylt så langt emne-filene er utfylt") 
```







```{r}
#| echo: false
#| warning: false
#| message: false

emneansvarlige %>%
  select(emne,  ends_with("1")) %>%
  #select(- 2) %>% 
  filter( !is.na(.[,2]) ) %>%  
  gt(rowname_col = "emne", groupname_col = "semester") %>% 
  sub_missing(columns = everything(),
              rows = everything(),
              missing_text = " " ) %>% 
  cols_align(align = "right") %>% 
  tab_header(title = "Emneansvarlige vårsemester", subtitle = "Utfylt så langt emne-filene er utfylt") 

```

